export default [
  { time: 11.62, text: "I'm sittin' here in the boring room" },
  { time: 16.11, text: "It's just another rainy Sunday afternoon" },
  { time: 18.85, text: "I'm wasting my time I got nothin' to do" },
  { time: 22.49, text: "I'm hangin' around I'm waitin' for you" },
  { time: 25.88, text: "But nothing ever happens and I wonder" },
  { time: 32.66, text: "I'm drivin' around in my car" },
  { time: 36.12, text: "I'm drivin' too fast I'm drivin' too far" },
  { time: 39.25, text: "I'd like to change my point of view" },
  { time: 42.77, text: "I feel so lonely I'm waitin' for you" },
  { time: 45.94, text: "But nothing ever happens and I wonder" },
  { time: 52.45, text: "I wonder how I wonder why" },
  { time: 56.20, text: "Yesterday you told me 'bout the blue blue sky" },
  { time: 59.18, text: "And all that I can see is just a yellow lemon tree" },
  { time: 65.94, text: "I'm turnin' my head up and down" },
  { time: 59.68, text: "I'm turnin', turnin', turnin', turnin', turnin' around" },
  { time: 72.69, text: "And all that I can see is just another lemon tree" },
  { time: 78.19, text: "Sing!" },
  { time: 79.84, text: "Dap-dadada-dadpm-didap-da" },
  { time: 85.00, text: "Dadada-dadpm-didap-da" },
  { time: 88.51, text: "Dap-didili-da" },
  { time: 92.78, text: "I'm sittin' here" },
  { time: 94.76, text: "I miss the power" },
  { time: 96.53, text: "I'd like to go out takin' a shower" },
  { time: 99.51, text: "But there's a heavy cloud inside my head" },
  { time: 103.02, text: "I feel so tired" },
  { time: 104.77, text: "Put myself into bed" },
  { time: 106.25, text: "Well, nothing ever happens and I wonder" },
  { time: 112.67, text: "Isolation is not good for me" },
  { time: 120.40, text: "Isolation, I don't want to sit on the lemon tree" },
  { time: 126.90, text: "I'm steppin' around in the desert of joy" },
  { time: 130.18, text: "Baby, anyhow I'll get another toy" },
  { time: 133.42, text: "And everything will happen and you wonder" },
  { time: 140.11, text: "I wonder how I wonder why" },
  { time: 143.31, text: "Yesterday you told me 'bout the blue blue sky" },
  { time: 148.57, text: "And all that I can see is just another lemon tree" },
  { time: 153.32, text: "I'm turnin' my head up and down" },
  { time: 156.82, text: "I'm turnin', turnin', turnin', turnin', turnin' around" },
  { time: 160.09, text: "And all that I can see is just a yellow lemon tree" },
  { time: 164.99, text: "And I wonder, wonder" },
  { time: 166.98, text: "I wonder how I wonder why" },
  { time: 170.24, text: "Yesterday you told me 'bout the blue blue sky" },
  { time: 173.23, text: "And all that I can see" },
  { time: 177.13, text: "And all that I can see" },
  { time: 180.39, text: "And all that I can see" },
  { time: 183.04, text: "Is just a yellow lemon tree" },
];