name: Build and Deploy React Application

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          npm install
          npm run build
          
      - name: Deploy react app to github pages
        run: |
          git config user.name "mvdegtyar"
          git config user.email "mv.degtyar@gmail.com"
          git remote set-url origin https://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@github.com/mvdegtyar/react-player.git
          npm run deploy
